{ config, pkgs, ... }:

{
  programs.zsh = {
    enable = true;

    shellAliases = {
      ls   = "ls --color";
      ll   = "ls -l --si";
      grep = "grep --color";
      wget = "wget --hsts-file=/dev/null";
    };

#    loginShellInit = ''
#      # ** DO NOT EDIT **
#      #
#      # Autogenerated by `/etc/nixos/sh_config.nix`
#      # Any changes will be overwritten on the next rebuild-switch
#      PROMPT="[ %(!.%F{red}.%F{cyan})%n %F{reset}@ %F{yellow}%m %F{reset}]%# "
#      RPROMPT="[ %F{blue}%~ %F{reset}: %F{magenta}%? %F{reset}]"
#    '';

    histFile = "$HOME/.cache/zsh_history";
  };
}
